
OUTPUT_INFO <- list(
  table_summary = 'The purpose of these table(s) is to summarise the results for the comparison of the various optima that arise under the different optimality criteria for what makes a ‘good’ bed-net. The first column (Optimum Type) contains a coded description of the optimality criterion. To start with: ‘Joint’ refers to an optimum across loadings of both insecticides, ‘Solo 1’ refers to an optimum when the second insecticide has a loading of 0 (so the optimum is just across the use of the first insecticide) and ‘Solo 2’ refers to an optimum when the first insecticide has a loading of 0 (so the optimum is just across the use of the second insecticide). After this: there is a two-letter abbreviation that describes what is maximised, as detailed in the welcome page and matching the tabs at the side of the page (that allow optimal criteria to be explored in greater detail). The second to fourth columns describe the bed-net lifespan and insecticide loadings. The fifth column (Bed-Net Coverage of Human Population) describes the percentage of the human population that receives a bed-net, which is contingent upon the public health budget per household for the purchase of bed-nets and the cost per bed-net, which is outlined in the following column (Cost per Bed-Net in USD; for Rotations/Mosaics there are two columns for each bed-net, where bed-net 1 has the first insecticide and bed-net 2 has the second insecticide). The next column (Average Control over Simulation Timespan) describes the percentage reduction in the population size compared to the carrying capacity averaged across all mosquito generations within the simulation. Finally, the last columns (Bioefficacy of 3 Year-Old Bed-Net at Simulation Start and Bioefficacy of 3 Year-Old Bed-Net at Simulation End; for Rotations/Mosaics there are two columns each per bed-net) describes the mortality of a bed-net that is tested in a standard bioassay (a cone test) after it has been used for 3 years in the field at the start and end of the simulation (where their difference reflects resistance evolution). Rows with ‘-‘ indicate that there are no bed-nets within the optimisation range of the simulation that satisfy the optimality criteria, which is either because a bed-net does not have >80% mortality after 3 years use due to resistance or because the public health budget per household for the purchase of bed-nets is insufficient to achieve universal coverage.',
  input_curves = 'The purpose of these figures is to describe how the properties of bed-nets vary over their deployment lifespan, which constitute the inputs that result in different impacts on vector control and resistance evolution. The y-axis runs from 0 to the maximum deployment lifespan of a bed-net for the optimum. In the row of three figures that are produced for each simulation, the first figure describes the chemical decay in the loading of insecticides on a bed-net over time, the second figure describes the effect that this chemical decay has on the proportional mortality of mosquitoes with exposure to the bed-net in a bioassay (a cone test) and the third figure describes the proportion of bed-nets that are in-use, which is lowered by people not using a bed-net that is given to them and by damage to bed-nets over time. The total mortality effect of a bed-net with a mixture of insecticides comes from the product of their independent mortality effects.',
  output_dynamics = 'The purpose of these figures is to describe the impact of the optimum on the mosquitoes over the course of the simulation timespan, which reveals whether the optimum produces a short or sustained reduction in mosquito population size and what the implications are for resistance evolution. The vertical grey-line indicates the deployment lifespan of a bed-net. In the row of three figures that are produced for each simulation, the first figure shows the effect of the bed-net on the number of mosquitoes in the target population, the second figure shows the effect of each insecticide on resistance allele(s) to that insecticide and the third figure shows the resistance phenotype as would be measured in a standard bioassay (a cone test) for a solo-insecticide bed-net (with the given relative loading) that has been used for 3 years in the field. The lines in the second and third figures can be discontinuous when there are multiple resistance alleles, where plotting switches from the spread of one resistance allele to an insecticide to the spread of a subsequent resistance allele to that same insecticide. Resistance to the insecticides is assumed to evolve at independent loci.',
  vector_control = 'The purpose of these figures is to describe the extent of vector control through slices of the parameter space that centre around the optimum to highlight other near-optimal combinations. The extent of vector control is shown by a colour scale from the minimum of no change in the mosquito population size in yellow to the maximum change in the mosquito population size provided by the maximum vector control (MC) optimum in purple. The white circle indicates the optimum, as defined by the optimality criteria that is being looked at. The white lines show the contours of the vector control surface. In the row of three figures that are produced for each simulation, the first figure shows the extent of vector control through the dimensions of the relative loading of the first insecticide and the deployment lifespan of the bed-net whilst the relative loading of the second insecticide is constant (at the optimum), the second figure shows the extent of vector control through the dimensions of the relative loading of the second insecticide and the deployment lifespan of the bed-net whilst the relative loading of the first insecticide is constant (at the optimum) and the third figure shows the extent of vector control through the dimensions of the relative loading of the first and second insecticides whilst the deployment lifespan of the bed-net is constant (at the optimum).',
  coverage = 'The purpose of these figures is to describe the extent of bed-net coverage through slices of the parameter space that centre around the optimum to explore the relationship that universal coverage has to the optimum. The extent of bed-net coverage is shown by a colour scale from the minimum of 0% in purple to the maximum of 100% in yellow. The black circle indicates the optimum, as defined by the optimality criteria that is being looked at. The black lines show the contours of the bed-net coverage surface. In the row of three figures that are produced for each simulation, the first figure shows the extent of bed-net coverage through the dimensions of the relative loading of the first insecticide and the deployment lifespan of the bed-net whilst the relative loading of the second insecticide is constant (at the optimum), the second figure shows the extent of bed-net coverage through the dimensions of the relative loading of the second insecticide and the deployment lifespan of the bed-net whilst the relative loading of the first insecticide is constant (at the optimum) and the third figure shows the extent of bed-net coverage through the dimensions of the relative loading of the first and second insecticides whilst the deployment lifespan of the bed-net is constant (at the optimum).',
  bednet_cost = 'The purpose of these figures is to describe the relative costs of bed-nets through slices of the parameter space that centre around the optimum to explore the relationship that bed-net cost has to the optimum. The relative costs of bed-nets are shown by a colour scale from the minimum of the base cost of an untreated bed-net in purple to the maximum of the cost of a bed-net with maximal loading of both insecticides in yellow. The white circle indicates the optimum, as defined by the optimality criteria that is being looked at. The white lines show the contours of the bed-net coverage surface. In the row of three figures that are produced for each simulation, the first figure shows the relative costs of bed-nets through the dimensions of the relative loading of the first insecticide and the deployment lifespan of the bed-net whilst the relative loading of the second insecticide is constant (at the optimum), the second figure shows the relative costs of bed-nets through the dimensions of the relative loading of the second insecticide and the deployment lifespan of the bed-net whilst the relative loading of the first insecticide is constant (at the optimum) and the third figure shows the relative costs of bed-nets through the dimensions of the relative loading of the first and second insecticides whilst the deployment lifespan of the bed-net is constant (at the optimum).'
)

UPDATE_FUNCTIONS <- list(
  
  # basic
  os = "updateTextInput",
  xb = 'updateNumericInput',
  iA = "updateTextInput",
  iB = "updateTextInput",
  
  # advanced
  # p1
  og = 'updateNumericInput',
  oy = 'updateNumericInput',
  ol = 'updateNumericInput',
  oi_b = 'updateNumericInput',
  oi_c = 'updateNumericInput',
  ou = 'updateNumericInput',
  er = 'updateNumericInput',
  ek = 'updateNumericInput',
  el = 'updateNumericInput',
  xn = 'updateNumericInput',
  mrx1 = 'updateNumericInput',
  xs1 = 'updateNumericInput',
  xs2 = 'updateNumericInput',
  pm = 'updateNumericInput',
  p0 = 'updateNumericInput',
  p3 = 'updateNumericInput',
  # p2
  mrx6 = 'updateNumericInput',
  iX6 = "updateTextInput",
  iX6_abb = "updateTextInput",
  cd6 = 'updateNumericInput',
  md6 =  'updateNumericInput',
  mh6 = 'updateNumericInput',
  xu6 = 'updateNumericInput',
  mrx7 = 'updateNumericInput',
  iX7 = "updateTextInput",
  iX7_abb = "updateTextInput",
  cd7 = 'updateNumericInput',
  md7 =  'updateNumericInput',
  mh7 = 'updateNumericInput',
  xu7 = 'updateNumericInput'
)

DEFAULTS <- list(
  
  # basic
  os = "Mixture", # strategy : "Mixture", "Rotation", "Mosaic"
  xb = 2,
  iA = "Pyrethroid",
  iB = "New AI 1",
  
  # advanced
  # p1
  og = 12,
  oy = 12,
  ol = 4,
  oi_b = 0.25,
  oi_c = 0.2,
  ou = 10^-6,
  er = 1,
  ek = 10^9,
  el = 0.5,
  xn = 1.8,
  mrx1 = 2,
  xs1 = 0,
  xs2 = 0,
  pm = 0.88,
  p0 = 0.995711963,
  p3 = 0.464204692,
  # p2
  mrx6 = 0,
  iX6 = "New AI 1",
  iX6_abb = "NW1",
  cd6 = 0.02067709,
  md6 = -0.0312781,
  mh6 = 2.512306,
  xu6 = 2.50,
  mrx7 = 0,
  iX7 = "New AI 2",
  iX7_abb = "NW2",
  cd7 = 0.02067709,
  md7 = -0.0312781,
  mh7 = 2.512306,
  xu7 = 2.50
)

N_SIM_ROWS <- 3

INFO <- list(
  os='Options are Mixture, Rotation and Mosaic. Mixtures involve both insecticides on one bed-net. Rotations involve switching the in-use bed-net, where bed-nets only have one insecticide. Mosaics involve the deployment of bed-nets with one insecticide, where each has is deployed at equal frequency.',
  xb='The money in USD that a public health organisation has to spend on the purchasing of bed-nets per household within a malarious area where bed-nets are to be deployed.',
  iA='The designation of an insecticide as first or second is arbitrary, except for Rotations, where the first insecticide is deployed first. Additional insecticides beyond those listed can be simulated using the Expert tab.',
  iB='The designation of an insecticide as first or second is arbitrary, except for Rotations, where the first insecticide is deployed first. Additional insecticides beyond those listed can be simulated using the Expert tab.',
  og='The number of mosquito generations that occur over the course of one year, which are plotted assuming that these generations occur evenly throughout the year.',
  oy='This parameter controls two properties: the number of years that simulations are run over, and the maximum bed-net lifespan that a bed-net can be deployed for. NB: modifying this parameter can alter simulation run-time.',
  ol='The maximum chemical loading of each insecticide that can be put into a bed-net in relative units (where the baseline chemical loading is 1). NB: modifying this parameter can alter simulation run-time.',
  oi_b='The interval to search across bed-net lifespans for the optimisation process, in units of years of bed-net deployment. NB: modifying this parameter can alter simulation run-time.',
  oi_c='The interval to search across chemical loadings for the optimisation process, in relative units of insecticide concentration (where the baseline chemical loading is 1) . NB: modifying this parameter can alter simulation run-time.',
  ou='The mutation rate that generates new resistance mutations (excluding the first resistance mutation that pre-exists), where are assumed to spread sequentially. This parameter determines the lag-time between the near-fixation of one resistance mutation and the origin of a subsequent resistance mutation.',
  er='The maximum rate of population increase, as defined as r in the logistic model of population change.',
  ek='The maximum sustainable population size, as defined as K in the logistic model of population change.',
  el='The proportional reduction in mortality that is conferred by an individual carrying a single resistance mutation, which applies to the resistance mutations for all insecticides.',
  xn='The cost of the fabric needed for a bed-net in USD, which is the baseline cost for a bed-net that contains no insecticides.',
  mrx1='The number of pyrethroid resistance mutations that have fixed prior to the start of the simulations, which interacts with the proportional reduction in mortality from a resistance mutation to determine initial insecticide efficacy.',
  xs1='The proportional cost of the first insecticide that is subsidised to reduce the unit cost of a bed-net. This is a specific kind of subsidy that may reduce the cost of new insecticides; to subsidise the total cost of the bed-net, increase the public health budget parameter.',
  xs2='The proportional cost of the second insecticide that is subsidised to reduce the unit cost of a bed-net. This is a specific kind of subsidy that may reduce the cost of new insecticides; to subsidise the total cost of the bed-net, increase the public health budget parameter.',
  pm='The proportion of bed-nets that are distributed to users (i.e. have coverage) but are not installed by users, such that they neither provide a physical barrier nor an insecticidal effect.',
  p0='The proportion of bed-nets that are purchased but that lose their physical barrier to biting upon distribution to users due to damage to the physical integrity of the fabric.',
  p3='The proportion of bed-nets that remain a physical barrier to biting after 3 years of installation by users.',
  mrx6='The number of New AI 1 resistance mutations that have fixed prior to the start of the simulations, which interacts with the proportional reduction in mortality from a resistance mutation to determine initial insecticide efficacy.',
  iX6='The name of New AI 1 for use in plot legends. NB: do not rename to the existing name of one of the other insecticides.',
  iX6_abb='The abbreviated name of New AI 1 for use in plot legends. NB: do not rename to the existing abbreviated name of one of the other insecticides.',
  cd6='The rate of chemical decay of New AI 1 on bed-nets, which follows a negative exponential curve. NB: this number can seem arbitrary, but can be tested to visualise what this decay rate means.',
  md6='The rate of decay in the mortality effect of New AI 1 on bed-nets, which is a logistic curve parameter. NB: this number can seem arbitrary, but can be tested to visualise what this decay rate means.',
  mh6='The half-life of decay in the mortality effect of New AI 1 on bed-nets, which is a logistic curve parameter. NB: this number can seem arbitrary, but can be tested to visualise what this decay rate means.',
  xu6='The cost of each relative unit of New AI 1 that is used a bed-net in USD, which a significant factor in the coverage of bed-nets that can be achieved.',
  mrx7='The number of New AI 2 resistance mutations that have fixed prior to the start of the simulations, which interacts with the proportional reduction in mortality from a resistance mutation to determine initial insecticide efficacy.',
  iX7='The name of New AI 2 for use in plot legends. NB: do not rename to the existing name of one of the other insecticides.',
  iX7_abb='The abbreviated name of New AI 2 for use in plot legends. NB: do not rename to the existing abbreviated name of one of the other insecticides.',
  cd7='The rate of chemical decay of New AI 2 on bed-nets, which follows a negative exponential curve. NB: this number can seem arbitrary, but can be tested to visualise what this decay rate means.',
  md7='The rate of decay in the mortality effect of New AI 1 on bed-nets, which is a logistic curve parameter. NB: this number can seem arbitrary, but can be tested to visualise what this decay rate means.',
  mh7='The half-life of decay in the mortality effect of New AI 2 on bed-nets, which is a logistic curve parameter. NB: this number can seem arbitrary, but can be tested to visualise what this decay rate means.',
  xu7='The cost of each relative unit of New AI 2 that is used a bed-net in USD, which a significant factor in the coverage of bed-nets that can be achieved.',
  xs='The proportional cost of the first and second insecticide that is subsidised to reduce the unit cost of a bed-net. This is a specific kind of subsidy that may reduce the cost of new insecticides; to subsidise the total cost of the bed-net, increase the public health budget parameter.',
  mr_set='The proportional reduction in mortality to each insecticide, which depends on the number and mortality-reduction effect of resistance mutations. NB: this set is a derivative of other parameters.',
  iX_set='The names of all insecticides that can be simulated. NB: this set is a derivative of other parameters.',
  iX_abb='The abbreviated names of all insecticides that can be simulated. NB: this set is a derivative of other parameters.',
  cd_set='The rate of chemical decay of all insecticides that can be simulated on bed-nets. NB: this set is a derivative of other parameters.',
  md_set='The rate of mortality decay of all insecticides that can be simulated on bed-nets. NB: this set is a derivative of other parameters.',
  mh_set='The half-life of mortality decay of all insecticides that can be simulated on bed-nets. NB: this set is a derivative of other parameters.',
  xu_set='The cost of each relative unit of insecticides that can be simulated on bed-nets in USD. NB: this set is a derivative of other parameters.'
)

PARAMETER_MAP <- list(
  os='Resistance-management strategy',
  xb='Public health budget per household for purchasing bed-nets in USD',
  iA='Name of the first insecticide',
  iB='Name of the second insecticide',
  og='Mosquito generations per year',
  oy='Number of years of simulation; maximum bed-net lifespan',
  ol='Maximum chemical loading onto a bed-net',
  oi_b='Search interval for bed-net lifespan',
  oi_c='Search interval for chemical loading',
  ou='Subsequent resistance mutation rate',
  er='Mosquito population growth rate',
  ek='Mosquito population carrying capacity',
  el='Proportional resistance confered by a resistance mutation',
  xn='Base cost of an untreated bed-net in USD',
  mrx1='Initial number of fixed pyrethroid resistance mutations',
  xs1='Proportional subsidy of the first insecticide',
  xs2='Proportional subsidy of the second insecticide',
  pm='Proportional use of bed-nets provided',
  p0='Proportional survival of bed-nets on arrival',
  p3='Proportional survival of bed-nets after 3 years of use',
  mrx6='Initial number of fixed resistance mutations to New AI 1',
  iX6='Name of New AI 1',
  iX6_abb='Abbreviated name of New AI 1',
  cd6='Rate of chemical decay of New AI 1 on bed-nets',
  md6='Rate of mortality decay of New AI 1 on bed-nets',
  mh6='Half-life of mortality decay of New AI 1 on bed-nets',
  xu6='Cost per relative unit of New AI 1 in USD',
  mrx7='Initial number of fixed resistance mutations to New AI 2',
  iX7='Name of New AI 2',
  iX7_abb='Abbreviated name of New AI 2',
  cd7='Rate of chemical decay of New AI 2 on bed-nets',
  md7='Rate of mortality decay of New AI 2 on bed-nets',
  mh7='Half-life of mortality decay of New AI 2 on bed-nets',
  xu7='Cost per relative unit of New AI 2 in USD',
  xs='Proportional subsidy of insecticides',
  mr_set='Proportional initial resistance to insecticides',
  iX_set='Names of insecticides',
  iX_abb='Abbreviated names of insecticides',
  cd_set='Rate of chemical decay of insecticides on bed-nets',
  md_set='Rate of mortality decay of insecticides on bed-nets',
  mh_set='Half-life of mortality decay of insecticides on bed-nets',
  xu_set='Cost per relative unit of insecticides in USD'
)
